// ── All Queue DTO Contracts (SRS §4.2) ───────────────────────────────────────

export interface BaseJobDTO {
  jobId: string;            // UUIDv4 — generated by producer
  jobType: string;
  platform: string;         // 'instagram' | 'linkedin' | 'youtube'
  schemaVersion: 'v1';
  metadata: {
    trigger: 'scheduler' | 'manual' | 'event';
    attempt: number;
    initiatedBy: string;    // 'system' | admin ref
  };
  createdAt: string;        // ISO 8601 UTC
}

// ── scrapeQueue ──────────────────────────────────────────────────────────────
export interface ScrapeJobDTO extends BaseJobDTO {
  jobType: 'SCRAPE_FEED' | 'SCRAPE_KEYWORD' | 'SCRAPE_PROFILE';
  targetType: 'feed' | 'keyword' | 'profile';
  targetValue?: string;     // keyword string or profileId; undefined for feed
  scrapeJobDbId: string;    // UUID → scrape_jobs.id (audit log)
}

// ── parseQueue ───────────────────────────────────────────────────────────────
export interface ParseJobDTO extends BaseJobDTO {
  jobType: 'PARSE_POST_HTML' | 'PARSE_POST_API' | 'PARSE_POST_GRAPHQL';
  rawPayloadId: string;     // UUID → raw_payloads.id
  payloadType: 'html' | 'api_json' | 'graphql';
  sourceType: 'feed' | 'keyword' | 'profile';
}

// ── thresholdQueue ───────────────────────────────────────────────────────────
export interface ThresholdJobDTO extends BaseJobDTO {
  jobType: 'EVALUATE_THRESHOLD';
  postDTO: NormalizedPostDTO;
  rawPayloadId: string;     // For updating parse_status after evaluation
}

// ── THE universal data contract — every downstream module uses this shape ────
export interface NormalizedPostDTO {
  platform: string;           // 'instagram' | 'linkedin' | 'youtube'
  platformPostId: string;     // Platform-native post ID
  authorId?: string;
  authorUsername?: string;
  caption?: string;           // HTML-stripped
  hashtags: string[];         // lowercase, no '#', deduplicated
  likes: number;
  comments: number;
  shares: number;
  views: number;
  sourceType: 'feed' | 'keyword' | 'profile';
  postedAt?: string;          // ISO 8601 UTC (nullable)
  scrapedAt: string;          // ISO 8601 UTC
  rawPayloadId: string;       // UUID of raw_payloads record
  schemaVersion: 'v1';
}

// ── intelligenceQueue ────────────────────────────────────────────────────────
export interface IntelligenceJobDTO extends BaseJobDTO {
  jobType: 'EVALUATE_TREND';
  postDbId: string;       // Primary key from the `posts` table
  platformPostId: string;
  likes: number;
  comments: number;
  views: number;
  postedAt?: string;      // Used for time-decay gravity
  hashtags: string[];
}
